export type CompanyId = string;

export interface Company {
    id: string;
    ticker: string | null;
    name: string | null;
    lei: string | null;
    legal_name: string | null;
    stock_exchange: string | null;
    sic: number | null;
    short_description: string | null;
    long_description: string | null;
    ceo: string | null;
    company_url: string | null;
    business_address: string | null;
    mailing_address: string | null;
    business_phone_no: string | null;
    hq_address1: string | null;
    hq_address2: string | null;
    hq_address_city: string | null;
    hq_address_postal_code: string | null;
    entity_legal_form: string | null;
    cik: string | null;
    latest_filing_date: string | null;
    hq_state: string | null;
    hq_country: string | null;
    inc_state: string | null;
    inc_country: string | null;
    employees: number | null;
    entity_status: string | null;
    sector: string | null;
    industry_category: string | null;
    industry_group: string | null;
    template: string | null;
    standardized_active: boolean | null;
    first_fundamental_date: string | null;
    last_fundamental_date: string | null;
    first_stock_price_date: string | null;
    last_stock_price_date: string | null;
    thea_enabled: boolean | null;
    legacy_sector: string | null;
    legacy_industry_category: string | null;
    legacy_industry_group: string | null;
}